(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const el=(tag,text)=>{const node=document.createElement(tag);if(text!=null)node.textContent=text;return node;};
  const sources={instagram:'Instagram',facebook:'Facebook',website:'Agent website',brokerage:'Brokerage',zillow:'Zillow',realtor:'Realtor.com',listing:'Individual listing'};
  let data={cases:[],contacts:[],questions:[],services:[]},current=null,busy=false,pendingWrite=false,authorized=false,dirty=false,researchDirty=false,poll=null,lockedControls=null,meetingBaseline='',researchBaseline='';
  const requestedContact=new URLSearchParams(location.search).get('contact');
  const states={queued:'Queued for public research',researching:'Finding public evidence',collecting:'Collecting confirmed profiles',generating:'Generating the full audit',pre_ready:'Pre-meeting audit ready',meeting_saved:'Meeting answers saved',full_ready:'Full audit ready',needs_attention:'Needs attention'};
  const waiting=()=>!!current&&['queued','researching','collecting','generating'].includes(current.status);
  const changed=()=>window.sereneEmbeddedChanged?.();
  function message(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
  function readAnswers(){return Object.fromEntries(data.questions.map(q=>[q.id,$('answer-'+q.id)?.value||'']));}
  function selectedServices(){return data.services.filter(s=>$('service-'+s.id)?.checked).map(s=>s.id);}
  function meetingDraft(){return JSON.stringify({answers:Object.fromEntries(data.questions.map(q=>[q.id,($('answer-'+q.id)?.value||'').trim()])),services:selectedServices().sort(),notes:($('service-notes')?.value||'').trim()});}
  function researchDraft(){return JSON.stringify({sources:Object.keys(sources).map(id=>[id,!!$('source-'+id)?.checked,($('url-'+id)?.value||'').trim()]),identity:!!$('identity')?.checked,credits:!!$('credits')?.checked});}
  function syncDirty(){dirty=!!current&&!!meetingBaseline&&meetingDraft()!==meetingBaseline;researchDirty=!!current&&!!researchBaseline&&researchDraft()!==researchBaseline;return dirty||researchDirty;}
  const unsaved=()=>syncDirty();
  window.sereneEmbeddedDirty=()=>unsaved()||pendingWrite;
  function draftChanged(){syncDirty();updateProgress();message(dirty?'Meeting answers have unsaved changes.':researchDirty?'Public research fields have unsaved changes.':'Your entries match the saved audit.');changed();}
  async function api(path,method='GET',body){
    if(method!=='GET'){pendingWrite=true;changed();}
    const response=await fetch('/api/audits'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
    if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Your session could not be verified. Refresh the CRM and sign in again.');
    const value=await response.json();if(!response.ok)throw Error(value.error||'Audit request failed.');return value;
  }
  function lockControls(){if(!busy||!lockedControls)return;for(const control of document.querySelectorAll('button,input,select,textarea')){if(!lockedControls.has(control))lockedControls.set(control,control.disabled);control.disabled=true;}}
  function applyAvailability(){const pending=waiting();for(const form of [$('meeting'),$('research')])form?.querySelectorAll('button,input,select,textarea').forEach(control=>control.disabled=pending);if($('refresh-report'))$('refresh-report').disabled=pending;if($('retry'))$('retry').disabled=pending;$('start').disabled=!data.contacts.length;$('sample').disabled=!authorized;lockControls();}
  async function action(fn){
    if(busy)return;busy=true;lockedControls=new Map();lockControls();$('detail').setAttribute('aria-busy','true');
    try{await fn();}catch(error){message(error.message,true);}
    finally{busy=false;pendingWrite=false;lockedControls.forEach((disabled,control)=>{if(control.isConnected)control.disabled=disabled;});lockedControls=null;$('detail').removeAttribute('aria-busy');applyAvailability();changed();}
  }
  function notifyDocuments(){if(window.parent!==window)window.parent.postMessage({type:'serene-audit-documents-updated'},location.origin);}
  function renderList(){
    const query=$('search').value.trim().toLowerCase();$('cases').replaceChildren();const rows=data.cases.filter(c=>[c.contact.name,c.contact.email,c.contact.phone,c.contact.brokerage,c.status].filter(Boolean).join(' ').toLowerCase().includes(query));
    if(!rows.length){const empty=el('p',query?'No audits match this contact name.':'No audits yet. A saved Demo scheduled deal will appear here automatically.');empty.className='empty-state';$('cases').append(empty);}
    for(const item of rows){const button=el('button',item.contact.name);button.type='button';button.className='contact'+(current?.id===item.id?' active':'');button.setAttribute('aria-pressed',String(current?.id===item.id));button.append(el('small',(item.sample?'Fictional sample · ':'')+(states[item.status]||item.status)+' · '+new Date(item.created_at).toLocaleDateString('en-US')));button.onclick=()=>{if(busy||unsaved()&&!confirm('Leave unsaved meeting answers or research fields?'))return;current=item;renderDetail();renderList();};$('cases').append(button);}lockControls();
  }
  async function load(keep=true){
    const next=await api('');authorized=true;data=next;const wanted=current?.id;current=data.cases.find(c=>c.id===wanted)||data.cases.find(c=>c.contact_id===requestedContact)||null;
    const select=$('contact-start'),selectedContact=select.value;select.replaceChildren();for(const contact of data.contacts){const option=el('option',contact.name);option.value=contact.id;if(contact.id===(selectedContact||requestedContact))option.selected=true;select.append(option);}if(!data.contacts.length){const empty=el('option','No contacts available');empty.value='';select.append(empty);}
    renderList();if(!unsaved()||!keep)renderDetail();applyAvailability();schedule();
  }
  function schedule(){clearTimeout(poll);if(data.cases.some(c=>['queued','researching','collecting','generating'].includes(c.status)))poll=setTimeout(()=>{if(!busy&&!unsaved())load().catch(error=>{message(error.message,true);schedule();});else schedule();},5000);}
  function updateProgress(){const total=data.questions.filter(q=>q.required).length,complete=data.questions.filter(q=>q.required&&$('answer-'+q.id)?.value.trim()).length;if($('meeting-progress'))$('meeting-progress').textContent=complete+' of '+total+' questions answered. '+(complete===total?'Ready to generate the full audit.':'Draft answers can be saved now.');}
  async function save(){const response=await api('/'+current.id+'/answers','PUT',{revision:current.revision,answers:readAnswers(),services:selectedServices(),serviceNotes:$('service-notes').value});current={...current,...response.audit};meetingBaseline=meetingDraft();syncDirty();return current;}
  function fillSampleAnswers(){
    if(!current?.sample||busy||unsaved()&&!confirm('Replace this unsaved draft with the fictional sample meeting answers?'))return;
    return action(async()=>{
      message('Loading the fictional meeting example…');const example=await api('/'+current.id);
      if(!example.sample||!example.sampleAnswers)throw Error('Sample meeting answers are unavailable. Refresh and try again.');
      for(const question of data.questions)$('answer-'+question.id).value=example.sampleAnswers[question.id]||'';
      for(const service of data.services)$('service-'+service.id).checked=example.sampleServices?.includes(service.id)||false;
      $('service-notes').value=example.sampleServiceNotes||'';draftChanged();message('Fictional meeting answers added to this draft. Review them, save, then generate the full sample audit.');
    });
  }
  function renderDetail(){
    dirty=false;researchDirty=false;meetingBaseline='';researchBaseline='';
    if(!current){$('detail').replaceChildren(el('p','Select a contact to review their audit.'));changed();return;}
    $('detail').replaceChildren($('case-template').content.cloneNode(true));$('contact-name').textContent=current.contact.name;$('case-status').textContent=states[current.status]||current.status;
    $('sample-notice').hidden=!current.sample;$('sample-answers').hidden=!current.sample;$('sample-answers').onclick=fillSampleAnswers;$('research-panel').hidden=!!current.sample;
    for(const report of current.reports||[]){const row=el('div');row.className='report';const link=el('a',report.kind==='pre'?'Open pre-meeting audit':'Open full audit and proposal');link.href='/api/audits/reports/'+encodeURIComponent(report.id);link.target='_blank';link.rel='noopener';row.append(link,el('small',new Date(report.created_at).toLocaleString('en-US')));$('reports').append(row);}if(!current.reports?.length)$('reports').append(el('p','The pre-meeting document will appear when research finishes.'));
    $('refresh-report').onclick=()=>action(async()=>{syncDirty();if(dirty)throw Error('Save meeting answers first.');if(researchDirty)throw Error('Collect the entered research fields before regenerating, or refresh to discard them.');message('Generating a new pre-meeting document from saved evidence…');await api('/'+current.id+'/refresh-report','POST',{revision:current.revision});notifyDocuments();await load(false);message('New pre-meeting version generated from saved evidence.');});
    $('retry').hidden=current.status!=='needs_attention';$('retry').onclick=()=>action(async()=>{syncDirty();if(dirty)throw Error('Save meeting answers before retrying.');if(researchDirty)throw Error('Collect the entered research fields before retrying, or refresh to discard them.');message('Retrying pre-meeting generation…');await api('/'+current.id+'/retry','POST',{revision:current.revision});await load(false);message('Pre-meeting generation queued.');});
    for(const evidence of current.evidence||[]){const description=el('p',evidence.source+': '+evidence.status.replaceAll('_',' ')+'. '+(evidence.note||''));description.className='small';$('evidence-results').append(description);for(const candidate of evidence.candidates||[]){const row=el('p','Unconfirmed candidate: '+candidate.title+' '),link=el('a','Review profile');link.href=candidate.url;link.target='_blank';link.rel='noopener';row.append(link);$('evidence-results').append(row);}}
    for(const [id,name] of Object.entries(sources)){const wrap=el('div'),label=el('label');label.className='check';const check=el('input');check.type='checkbox';check.id='source-'+id;label.append(check,document.createTextNode(name));const url=el('input');url.type='url';url.id='url-'+id;url.placeholder='https://...';url.setAttribute('aria-label',name+' URL');url.oninput=()=>{$('identity').checked=false;};wrap.append(label,url);$('research-fields').append(wrap);}
    $('research').addEventListener('input',draftChanged);$('research').addEventListener('change',draftChanged);
    $('research').onsubmit=event=>{event.preventDefault();action(async()=>{syncDirty();if(dirty)throw Error('Save meeting answers before collecting evidence.');const selected=Object.keys(sources).filter(id=>$('source-'+id).checked),links=Object.fromEntries(selected.map(id=>[id,$('url-'+id).value.trim()]));if(!selected.length)throw Error('Select at least one public source.');if(selected.some(id=>!links[id]))throw Error('Add a URL for each selected source.');if(!$('identity').checked)throw Error('Confirm that these profiles belong to this contact.');message('Collecting confirmed evidence and preparing the updated report…');await api('/'+current.id+'/research','POST',{revision:current.revision,sources:selected,target:{links,identityConfirmed:true},allowPaid:$('credits').checked});researchBaseline=researchDraft();syncDirty();notifyDocuments();await load(false);message('Public evidence and pre-meeting document updated. Review any unavailable sources.');});};
    for(const question of data.questions){const label=el('label',question.label+(question.required?' *':'')),description=el('p',question.prompt);description.className='small';description.id='prompt-'+question.id;const input=el(question.type==='select'?'select':'textarea');input.id='answer-'+question.id;input.required=question.required;input.setAttribute('aria-describedby',description.id);if(question.type==='select'){const blank=el('option','Choose an answer');blank.value='';input.append(blank);for(const value of question.options)input.append(el('option',value));}else{input.rows=3;input.maxLength=4000;}input.value=current.answers?.[question.id]||'';input.oninput=draftChanged;label.append(description,input);$('questions').append(label);}
    for(const service of data.services){const label=el('label');label.className='check service';const check=el('input');check.type='checkbox';check.id='service-'+service.id;check.checked=current.services?.includes(service.id)||false;check.onchange=draftChanged;const content=el('div');content.append(el('strong',service.name+' · $'+service.price+'/month, indicative'),el('p','Serene Ops: '+service.we),el('p','Realtor: '+service.agent));label.append(check,content);$('services').append(label);}
    $('service-notes').value=current.service_notes||'';$('service-notes').oninput=draftChanged;$('suggest').onclick=()=>{const answers=readAnswers();for(const service of data.services)$('service-'+service.id).checked=data.questions.some(question=>question.module===service.id&&answers[question.id]==='Needs work');draftChanged();message('Services suggested from reported gaps. Review the selection and add scope notes.');};
    const saveDraft=()=>action(async()=>{message('Saving meeting answers…');await save();if(researchDirty){$('case-status').textContent=states[current.status]||current.status;data.cases=data.cases.map(item=>item.id===current.id?current:item);renderList();}else await load(false);message('Meeting answers saved. You can continue filling them in later.');});$('save').onclick=saveDraft;$('meeting').onsubmit=event=>{event.preventDefault();saveDraft();};
    $('generate').onclick=()=>{if(busy||!$('meeting').reportValidity())return;action(async()=>{syncDirty();if(researchDirty)throw Error('Collect the entered research fields before generating, or refresh to discard them.');message('Saving answers and generating the full audit and proposal…');await save();await api('/'+current.id+'/generate','POST',{revision:current.revision});notifyDocuments();await load(false);message('Full audit and proposed services generated. Review the document before sending.');});};
    meetingBaseline=meetingDraft();researchBaseline=researchDraft();updateProgress();applyAvailability();changed();
  }
  $('search').oninput=renderList;
  $('refresh').onclick=()=>action(async()=>{if(unsaved()&&!confirm('Reload and discard unsaved answers and research fields?'))return;message('Refreshing audits…');await load(false);message('Audits refreshed.');notifyDocuments();});
  $('start').onclick=()=>{if(busy||unsaved()&&!confirm('Leave unsaved answers or research fields and open this contact’s audit?'))return;action(async()=>{const contactId=$('contact-start').value;if(!contactId)throw Error('Choose a contact with a Demo scheduled deal.');message('Preparing the pre-meeting audit…');const result=await api('/start','POST',{contactId});await load(false);current=data.cases.find(item=>item.id===result.id);renderDetail();renderList();message(['queued','researching','collecting','generating'].includes(result.status)?'Pre-meeting audit queued. It will appear here when research finishes.':'Opened the existing audit. Its saved documents and meeting answers are retained.');});};
  $('sample').onclick=()=>{if(busy||unsaved()&&!confirm('Leave unsaved answers or research fields and open the fictional sample audit?'))return;action(async()=>{message('Preparing the fictional sample audit…');const result=await api('/sample','POST',{});notifyDocuments();await load(false);current=data.cases.find(item=>item.id===result.id);if(!current)throw Error('The sample was saved. Refresh the audit list to open it.');renderDetail();renderList();message(result.reused?'Opened the fictional sample. Its saved answers and documents are retained.':'Fictional pre-meeting sample ready. Use the sample meeting answers to test the full audit.');});};
  window.addEventListener('beforeunload',event=>{if(unsaved()||pendingWrite){event.preventDefault();event.returnValue='';}});
  action(async()=>{await load();message('Select a generated audit, or create a fictional sample. New demo deals generate automatically after they are saved.');});
})();
