// Deliberately fictional fixtures. These must never be sent to research providers.
export const SAMPLE_CONTACT_ID='c_audit_sample_morgan_taylor';
export const SAMPLE_DEAL_ID='audit-sample:morgan-taylor';
export const SAMPLE_NOTICE='Fictional sample for demonstrating the audit workflow. Morgan Taylor, this business, all figures, listing details and source excerpts are invented. No realtor was researched, and no results or account insights were retrieved.';
export const isSampleContact=c=>c?.id===SAMPLE_CONTACT_ID||c?.is_sample===true;
export const isSampleCase=row=>row?.contact_id===SAMPLE_CONTACT_ID;
export function sampleContact(user,stamp){return {id:SAMPLE_CONTACT_ID,name:'Sample — Morgan Taylor',brokerage:'Fictional example brokerage',city:'Example US market',state:'',timezone:'America/New_York',email:'',phone:'',status:'Not contacted',owner_user_id:user.id,owner:user.name||'Ibrar',services:[],created_at:stamp,is_sample:true,audit_sample:true,sample_kind:'audit_fixture',notes:SAMPLE_NOTICE};}

export const SAMPLE_ANSWERS={
 leadSources:'FICTIONAL MEETING ANSWER: Over the last 90 days: 24 portal inquiries, 9 referral inquiries and 7 website inquiries. Five client engagements came from three referrals and two portal leads. The agent can identify sources for those five engagements, but appointment counts for each channel are incomplete. These are illustrative figures, not verified results.',
 responseWorkflow:'FICTIONAL MEETING ANSWER: Portal notifications arrive on the agent’s phone and in email. Website submissions reach a shared inbox but do not create a CRM task. Social messages are checked between appointments. A five-lead example showed first manual replies ranging from 20 minutes to the following morning; there is no agreed coverage when the agent is showing homes. The agent wants an approved acknowledgement during business hours and a clear handoff for advice or urgent questions.',
 nurtureWorkflow:'FICTIONAL MEETING ANSWER: The database contains approximately 620 records. About 140 are tagged as prospects, but next-action dates are inconsistent. The agent relies on remembered conversations and a monthly newsletter; there is no documented 30-, 60- or 90-day follow-up plan. Permission and unsubscribe information need to be reviewed before enrolling records in any sequence. No bulk contact or record deletion has been authorized.',
 sellerReporting:'FICTIONAL MEETING ANSWER: Two active listings use separate spreadsheets. The MLS price is updated first, while website copy and social captions are updated later when the agent has time. Sellers receive verbal updates after showings, but no set weekly report. A recent illustrative price adjustment had a two-day delay before the website changed. Photography and property access are managed by the agent; all MLS changes and property claims require agent approval.',
 reviewWorkflow:'FICTIONAL MEETING ANSWER: The agent usually asks for an honest review in the closing thank-you message. The request is not tracked in the CRM, and no one checks whether a reminder is appropriate. The preferred improvement is a consistent, neutral request to eligible clients with permission, without incentives, selective positive-review requests or pressure. No review counts are supplied as actual business facts.',
 socialResults:'FICTIONAL MEETING ANSWER: The agent prepares two educational posts and one listing post in a typical week. The agent films original material and approves copy. Content preparation is consistent, but link clicks and inquiry attribution are not recorded reliably. Reach and booking figures are Unknown. The agent wants a simple monthly review of genuinely available insights and recorded inquiries rather than a follower-growth promise.',
 timeOwnership:'FICTIONAL MEETING ANSWER: The agent estimates six hours weekly on database updates, chasing inquiry follow-ups and listing administration. Retain client advice, showings, negotiation, pricing decisions, photography approval and brokerage compliance. Consider delegating agreed CRM cleanup, next-action tracking, approved lead follow-up and two-listing checklists. The agent must approve all outbound scripts and property updates before the first live use.',
 business:'FICTIONAL MEETING ANSWER: This is a fictional solo independent agent in an example US market, with 18 illustrative closed sides last year and two current example listings. The next 90-day goal is a documented response workflow, accurate listing updates and every agreed active prospect having a dated next action. These numbers only demonstrate the questions and are not production benchmarks or forecasts.',
 crmSystem:'FICTIONAL MEETING ANSWER: The agent uses an example CRM plus email and spreadsheets. Approximately 620 illustrative contact records include old imports and incomplete source tags. The agent currently owns updates and reporting. An initial review should use a limited authorized export to agree tagging, duplicate handling and source fields; no system access or data migration has been approved in this sample.',
 crmGap:'Needs work',leadGap:'Needs work',listingGap:'Needs work',transactionGap:'Consistent',inboxGap:'Unknown',marketingGap:'Consistent',websiteGap:'Needs work',
 details:'FICTIONAL MEETING ANSWER: The agent described the five-lead response sample, the two-day listing update delay, a spreadsheet seller tracker and a contract-to-close checklist with dated lender/title milestones. In this demonstration, these are hypothetical statements rather than records personally inspected. On a real call request redacted examples, trace one permitted website inquiry through to its CRM owner, compare two authorized listing updates and verify whether active prospects have an owner and next action. The working transaction checklist should be preserved unless evidence shows a gap.',
 constraints:'FICTIONAL MEETING ANSWER: A starting monthly operating budget of approximately $1,100 is illustrative. Proposed core scope is Listing management ($570), CRM and database ($210), and Lead handling ($265), for an indicative $1,045/month subject to written capacity and access rules. The agent retains website changes initially and will test inquiry routing with their existing provider; an additional website module needs a separate decision. Coverage hours, escalation rules, permitted contact methods and brokerage approvals must be agreed before live work.'
};
export const SAMPLE_SERVICES=['02','03','04'];
export const SAMPLE_SERVICE_NOTES='FICTIONAL PROPOSAL: Start with two authorized listing checklists, an agreed CRM sample cleanup and approved incoming-lead tracking. Serene Ops prepares administrative updates and reports; the realtor approves MLS/property claims, contact scripts, pricing, advice and all licensed decisions. Preserve the existing transaction process and content schedule. The realtor retains website changes and supplies redacted onboarding examples. This $1,045/month module illustration is not an accepted quote or a promise of outcomes; confirm scope, capacity, coverage and access in writing.';

const source=(id,key,text)=>({id,source:key,url:'',date:'Illustrative fixture — not an observation date',text});
const SOURCES=[
 source('EX1','instagram','ILLUSTRATIVE INSTAGRAM EXCERPT: Bio: Local home guidance, clear next steps. Message me for buying or selling. Example captions explain inspection preparation and promote a new listing, but the inquiry destination and expected reply timing are not stated.'),
 source('EX2','facebook','ILLUSTRATIVE FACEBOOK EXCERPT: The example business page includes the agent’s service description, a telephone contact and open-house announcements. An older property announcement still shows its original asking price after an illustrative price adjustment.'),
 source('EX3','website','ILLUSTRATIVE WEBSITE EXCERPT: Buying, selling and property-detail pages offer a contact form. The sample confirmation says: Thank you, your message has been received. It does not specify the expected next step. The form destination and CRM routing have not been tested.'),
 source('EX4','brokerage','ILLUSTRATIVE BROKERAGE EXCERPT: The example biography describes local guidance, clear communication and hands-on support. It gives the brokerage identity and a consistent telephone contact but no specific explanation of the listing launch or seller update process.'),
 source('EX5','zillow','ILLUSTRATIVE ZILLOW EXCERPT: Two invented review excerpts say: Explained each stage clearly; and Kept us informed through closing. These excerpts only demonstrate reputation analysis. Review counts, dates, rankings, production and account ownership are not real or assessed.'),
 source('EX6','realtor','ILLUSTRATIVE REALTOR.COM EXCERPT: The fictional directory profile includes the same agent name and brokerage as the other example channels. Its biography says: Helping buyers and sellers with clear guidance. No actual profile, production history or platform metrics were accessed.'),
 source('EX7','listing','ILLUSTRATIVE LISTING EXCERPT: Example Listing A is a three-bedroom home. The sample description names the rooms and nearby amenities, with photos and a request-information link. The website copy retains the original asking price while the example listing checklist records a newer price. Property facts, images and prices are invented, and no MLS was accessed.')
];
export function sampleEvidence(stamp){return SOURCES.map(s=>({source:s.source,status:'illustrative_sample',identityConfirmed:false,sample:true,collectedAt:stamp,note:SAMPLE_NOTICE,evidence:[{title:'Fictional '+s.source+' excerpt',text:s.text,url:'',imagesOmitted:true}]}));}
const finding=(tone,title,sourceId,quote,interpretation,action,example,measure)=>({tone,title,sourceId,quote,interpretation,action,example,measure});
export function sampleAnalysis(){return {generated:false,sample:true,note:SAMPLE_NOTICE,sources:SOURCES,sections:[
 {source:'instagram',title:'Instagram — illustrative review',findings:[
 finding('strength','A useful educational starting point','EX1','Example captions explain inspection preparation','The fictional excerpt gives buyers a concrete preparation topic. That can support a recognizable service promise, but an educational caption alone does not establish reach, lead quality or conversions. A real audit would review a dated, confirmed set of posts and actual available account insights.','Retain useful educational topics and connect each proposed post to one audience question and an appropriate next step. Keep original visuals and factual approvals with the realtor.','Proposed caption ending: Planning an inspection? Send your question and we will explain the next step for your situation.','With permission, record inquiries attributed to reviewed posts and the follow-up outcome. Do not treat likes or lifetime followers as clients.'),
 finding('opportunity','Make the inquiry handoff explicit','EX1','the inquiry destination and expected reply timing are not stated','This gap exists only in the illustrative text. It suggests a question about how a reader reaches the agent and what happens next; it does not prove that the real account lacks working links or replies. Verify the profile and one permitted inquiry before changing the journey.','Agree one approved contact route, its receiving owner and realistic business-hour response wording. Test the route and record the handoff before publishing.','Proposed bio line: Buying or selling? Use the contact link for a planning call. The agreed acknowledgement should explain when to expect a reply.','Track successful handoffs, inquiries without an owner and actual first-response time during the agreed coverage window.') ]},
 {source:'facebook',title:'Facebook — illustrative review',findings:[finding('opportunity','Keep property announcements synchronized','EX2','An older property announcement still shows its original asking price','In the example, a channel update is delayed. That could create inconsistent expectations for readers, but neither current Facebook visibility nor a real property’s price was assessed. The listing owner needs a single approved change record and a channel checklist.','After an approved listing change, record the effective date and check every authorized public destination. Assign an owner to confirm completion, and preserve the agent’s approval of price and property statements.','Illustrative checklist: agent approves price change → update authorized property pages → check live copy → update or clarify retained social announcements → log the verification.','Measure approved changes with all agreed channels verified and the time between approval and completed verification.')]},
 {source:'website',title:'Website and inquiry journey — illustrative review',findings:[
 finding('strength','Keep a direct inquiry route','EX3','Buying, selling and property-detail pages offer a contact form','The sample gives visitors a direct way to request help. Its presence is a starting point, not evidence that forms work or that submissions are logged. On a real account, the important operational question is whether a permitted test inquiry reaches a named owner.','Keep the useful route and test the complete journey from submission through acknowledgement, assignment and next action. Use a clearly identified test inquiry and permission from the account owner.','Proposed test record: source page, submission time, receiving inbox, CRM record, assigned owner, acknowledgement and next-action deadline.','Successful authorized tests across agreed inquiry routes; inquiries missing an owner or next action.'),
 finding('opportunity','Set expectations after submission','EX3','Thank you, your message has been received.','The invented confirmation acknowledges receipt but gives little direction. It cannot tell us how the underlying automation works. A clearer approved message should describe the next step while matching actual coverage and avoiding unsupported reply promises.','Agree confirmation copy and test whether the inquiry reaches the CRM. If routing is broken, fix that handoff before adding new campaigns or paid traffic.','Proposed confirmation: Thank you. Your request is with our team. We will reply during the agreed business hours; for time-sensitive questions, use the listed contact number.','Actual acknowledgement delivery, routing exceptions and elapsed time to a human reply; targets must be agreed, not assumed.')]},
 {source:'brokerage',title:'Positioning and brokerage — illustrative review',findings:[finding('opportunity','Explain the service in concrete steps','EX4','local guidance, clear communication and hands-on support','The fictional biography expresses a useful intent, but it does not explain how communication and listing support operate. This is a copy opportunity supported by the fixture, not a finding about a real realtor’s expertise or actual service quality.','Ask the realtor which operating steps they can reliably deliver. Turn the verified steps into concise buyer/seller language and obtain brokerage approval before publishing.','Proposed seller copy: We agree the launch checklist, confirm approved property information and set a regular update schedule. Publish only steps the agent has committed to deliver.','Approved service statements matched to a named owner and a documented process; periodically check that promised updates are delivered.')]},
 {source:'zillow',title:'Zillow profile and reviews — illustrative review',findings:[finding('strength','Preserve the communication theme','EX5','Kept us informed through closing','This invented review wording illustrates how an audit can connect a supported communication theme to a service process. It cannot establish review authenticity, sentiment distribution, total reviews, production or competitive standing. A real audit would cite the exact permitted public review and date.','If actual verified reviews support this theme, preserve the communication steps clients value and make the review-request process consistent and neutral. The realtor decides how client stories may be used.','Proposed internal process: after an eligible closing, record a neutral honest-review request and permitted follow-up; never require a positive rating.','Requests appropriately recorded and communication milestones delivered. Review volume is context, not a sales-performance score.')]},
 {source:'realtor',title:'Realtor.com profile — illustrative review',findings:[finding('opportunity','Use a consistent, specific service description','EX6','Helping buyers and sellers with clear guidance.','The fictional profile uses broad language. The fixture supports considering a more specific description, but no Realtor.com account, listing inventory or statistics were retrieved. Cross-channel consistency should be checked against a confirmed profile in a real audit.','Agree a short approved biography explaining market focus and verifiable service steps. Check public contact details across confirmed directories and keep a record of authorized update routes.','Proposed biography structure: whom you help → the market you actually serve → the process clients can expect → approved contact route and brokerage disclosures.','Confirmed directory details that match the approved source of truth and outstanding update requests.')]},
 {source:'listing',title:'Active listing presentation — illustrative review',findings:[
 finding('strength','Retain essential property facts and a next step','EX7','The sample description names the rooms and nearby amenities, with photos and a request-information link.','The fixture contains a basic property description and inquiry route. Photos are mentioned, but this text-only sample cannot establish photographic quality, staging, image rights, floor-plan quality or mobile appearance. Real listing advice should follow inspection of authorized materials and verified facts.','Preserve accurate essentials, then check approved assets, disclaimers and inquiry routing against a launch checklist. The realtor validates property claims and approves the final presentation.','Proposed launch record: approved facts, current price, asset permissions, publication destinations, tested inquiry route and named verification owner.','Listings with completed approved launch checklists; verified inquiry routes; unresolved factual or asset questions.'),
 finding('opportunity','Give each listing change a verification owner','EX7','The website copy retains the original asking price while the example listing checklist records a newer price.','The invented discrepancy demonstrates the type of concrete issue an audit can document. A real price mismatch must be supported by dated, confirmed evidence and checked with the realtor; an old cached page is not enough to conclude the live listing is wrong.','Maintain one approved change log, track each authorized channel and verify the live result. Send a concise regular seller update summarizing completed work, available feedback and next decisions without promising buyer demand.','Proposed weekly seller update: approved changes completed; available showing feedback; pending tasks; decisions requiring the seller and agent. No invented traffic or marketing results.','Time to verify an approved update across agreed channels; overdue listing tasks; seller updates delivered on the agreed schedule.')]}
 ]};}
export function labelSampleReport(report){return {...report,sample:true,sampleNotice:SAMPLE_NOTICE,title:'Sample — '+report.title,summary:SAMPLE_NOTICE+' '+(report.kind==='full'?'This version demonstrates how hypothetical meeting answers produce priorities, ownership and an indicative service proposal.':'This version demonstrates a public-information teaser using clearly labelled invented source excerpts; private workflows remain unassessed until the meeting.'),analysis:sampleAnalysis(),method:'Fictional demonstration using hand-written illustrative evidence and user-saved meeting answers. No internet research, paid connector credits, AI analysis, real listings, private account data or real client operations were used. Treat every number and observation as an example, and confirm all real findings and scope before sending an actual audit.'};}
