import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{transformContactArchiveTemplate}=require('./integrate-contact-archive.cjs');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),raw=JSON.parse(html.match(/<script type="__bundler\/template">([\s\S]*?)<\/script>/)[1]),template=transformContactArchiveTemplate(raw),code=template.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
const result=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json',ETag:'"next"'}});
function fixture({owner=false,readOnly=false}={}){
 const context={Date,Intl,JSON,Math,URL,URLSearchParams,structuredClone,console,setTimeout:()=>0,clearTimeout(){},DCLogic:class{setState(value,callback){this.state={...this.state,...(typeof value==='function'?value(this.state):value)};callback?.();}}};vm.createContext(context);vm.runInContext(code+';globalThis.ReviewComponent=Component;',context);const c=new context.ReviewComponent();
 c.state.authChecked=true;c.state.accessUser={id:owner?'u_ibrar':'u_sales',name:owner?'Fictional Owner':'Fictional Sales',email:owner?'owner@example.test':'sales@example.test',isOwner:owner,visibility:{profile:owner?'owner':'sales_associate',scope:'all_sales',sections:['contacts','pipeline','calls'],editSections:readOnly?[]:['contacts','pipeline','calls']}};c.state.meId=c.state.accessUser.id;c.state.db={users:[{id:c.state.meId,email:c.state.accessUser.email,name:c.state.accessUser.name}],contacts:[{id:'lead',name:'Fictional Realtor',status:'Not contacted',timezone:'America/New_York',notes:'Owner private preserved'},{id:'other',name:'Other Realtor'}],deals:[{id:'deal',contact_id:'lead'},{id:'other-deal',contact_id:'other'}],todos:[{id:'private-task',contact_id:'lead',title:'Pending operation'}],activity:[],user_prefs:{}};c.workspaceReady=()=>true;c.canSaveWorkspace=()=>true;c.toast=message=>{c.lastToast=message;};c._saveEpoch=0;c._savedEpoch=0;c._snapshotEtag='"prior"';c.state.bulk={};c.apiFetch=async()=>result({data:{ok:true,id:'lead',at:'2026-10-08T13:00:00Z',by:'Fictional Sales',byUserId:'u_sales',reason:'No longer interested',activity:{id:'archive-event',what:'Contact archived: No longer interested',contact_id:'lead'}},updatedAt:'next'});return c;
}

test('archive transform is repeat-safe and makes reason/actor evidence visible to owner',()=>{
 assert.equal(transformContactArchiveTemplate(template),template);assert.match(template,/<sc-if value="\{\{ canManageSalesContact \}\}"><button type="button" sc-camel-on-click="\{\{ cd.remove \}\}"/);assert.match(template,/Archived by \{\{ c.by \}\}/);assert.match(template,/\{\{ c.reason \}\}/);
});
test('sales archives use minimal canonical endpoint data and remove the contact/deals only after success',async()=>{
 const c=fixture();let call;c.apiFetch=async(path,options)=>{call={path,options};assert.equal(c.state.db.contacts[0].id,'lead');return result({data:{ok:true,id:'lead',at:'2026-10-08T13:00:00Z',by:'Fictional Sales',byUserId:'u_sales',reason:'No longer interested'},updatedAt:'next'});};assert.equal(await c.submitContactArchive('lead','  No longer interested  '),true);assert.equal(call.path,'/api/contact-archive');assert.equal(call.options.headers['If-Match'],'"prior"');assert.deepEqual(JSON.parse(call.options.body),{contactId:'lead',reason:'No longer interested'});assert.deepEqual(c.state.db.contacts.map(row=>row.id),['other']);assert.deepEqual(c.state.db.deals.map(row=>row.id),['other-deal']);assert.equal(c.state.db.todos[0].id,'private-task');assert.equal(c.state.contactId,null);assert.equal(c._snapshotEtag,'"next"');assert.equal(c._contactArchiveBusy,false);
});
test('owner local archive keeps evidence and private linked data; restore retains history',async()=>{
 const c=fixture({owner:true});await c.submitContactArchive('lead','No longer interested');const contact=c.state.db.contacts[0];assert.equal(contact.archive_reason,'No longer interested');assert.equal(contact.archived_by,'Fictional Sales');assert.equal(contact.notes,'Owner private preserved');assert.equal(c.state.db.deals.length,2);assert.equal(c.state.db.todos.length,1);c.restoreArchivedContactDb(c.state.db,'lead');assert.equal(contact.deleted_at,null);assert.equal(contact.archived_at,null);assert.equal(contact.archive_reason,'No longer interested');assert.equal(contact.archive_history.length,2);assert.equal(contact.archive_history[0].action,'Archived');assert.equal(contact.archive_history[1].action,'Restored');assert.equal(contact.archive_history[1].by_user_id,'u_ibrar');
});
test('reason, read-only permissions, pending saves and HTTP conflicts block local archiving',async()=>{
 const c=fixture();let calls=0;c.apiFetch=async()=>{calls++;return result({error:'This workspace changed.'},409);};for(const reason of ['', '  ', 'x'.repeat(2001)])await assert.rejects(c.submitContactArchive('lead',reason),/archive reason/);assert.equal(calls,0);await assert.rejects(fixture({readOnly:true}).submitContactArchive('lead','Reason'),/Contacts edit/);c._saveEpoch=1;c.flushDb=async()=>{};await assert.rejects(c.submitContactArchive('lead','Reason'),/finish saving/);assert.equal(calls,0);c._savedEpoch=1;await assert.rejects(c.submitContactArchive('lead','Reason'),/workspace changed/);assert.equal(c.state.db.contacts[0].deleted_at,undefined);assert.equal(c.state.db.deals.length,2);assert.equal(c._snapshotEtag,'"prior"');assert.equal(c._contactArchiveBusy,false);
});
test('double submission and changed access cannot copy an archived contact back into the workspace',async()=>{
 const c=fixture();let release,calls=0;c.apiFetch=async()=>{calls++;return new Promise(resolve=>{release=()=>resolve(result({data:{ok:true,id:'lead',at:'2026-10-08T13:00:00Z',reason:'Reason'},updatedAt:'next'}));});};const first=c.submitContactArchive('lead','Reason');assert.equal(await c.submitContactArchive('lead','Reason'),false);assert.equal(calls,1);c.workspaceReady=()=>false;release();await assert.rejects(first,/access changed/);assert.equal(c.state.db.contacts[0].deleted_at,undefined);assert.equal(c._contactArchiveBusy,false);
});
