import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {attachVisibility,isCrmAdministrator,isPrimaryOwner,scopeSnapshot,mergeScopedWrite,handleUsers,canonicalUsers} from './user-access.mjs';
const owner={id:'u_ibrar',orgId:'org1',name:'Primary owner',email:'owner@example.test',roleCode:'owner_admin',isOwner:true,isPrimaryOwner:true};
const administrator={id:'u_admin',orgId:'org1',name:'Fictional Administrator',email:'administrator@example.test',roleCode:'crm_admin',isOwner:true,isPrimaryOwner:false};
const contributor={id:'u_staff',orgId:'org1',name:'Fictional contributor',email:'staff@example.test',roleCode:'contributor',isOwner:false};
const request=(id='',method='GET',body)=>new Request('https://crm.test/api/users'+(id?'/'+id:''),{method,body:body?JSON.stringify(body):undefined});
const grant={name:'Fictional new administrator',email:'newadmin@example.test',status:'active',profile:'administrator',scope:'all',sections:[],editSections:[],administratorAcknowledged:true,invite:false};
function fixture({role=true}={}){
 const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE roles(id TEXT PRIMARY KEY,code TEXT NOT NULL,name TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL DEFAULT 'now');CREATE TABLE users(id TEXT PRIMARY KEY,org_id TEXT,name TEXT,email TEXT UNIQUE,role_id TEXT,status TEXT,created_at TEXT DEFAULT 'now',updated_at TEXT,deleted_at TEXT);CREATE TABLE user_visibility(org_id TEXT,user_id TEXT,sections_json TEXT,edit_sections_json TEXT,updated_at TEXT,access_profile TEXT CHECK(access_profile IN ('contributor','sales_associate')),record_scope TEXT CHECK(record_scope IN ('assigned','all_sales')),PRIMARY KEY(org_id,user_id));CREATE TABLE user_invitations(org_id TEXT,user_id TEXT,status TEXT,access_status TEXT,sent_at TEXT);INSERT INTO users VALUES('u_ibrar','org1','Primary owner','owner@example.test','role_owner','active','now',NULL,NULL);INSERT INTO users VALUES('u_staff','org1','Fictional contributor','staff@example.test','role_contributor','active','now',NULL,NULL);INSERT INTO users VALUES('u_admin','org1','Fictional Administrator','administrator@example.test','role_crm_admin','active','now',NULL,NULL);INSERT INTO user_visibility VALUES('org1','u_staff','[\"work\"]','[\"work\"]','now','contributor','assigned');");
 if(role)sql.exec(fs.readFileSync(new URL('./migrations/20261008_crm_administrator_role.sql',import.meta.url),'utf8'));
 const wrap=(s,v=[])=>({first:async()=>s.get(...v)||null,all:async()=>({results:s.all(...v)}),run:async()=>({meta:{changes:Number(s.run(...v).changes)}})}),env={DB:{prepare(q){const s=sql.prepare(q);return {...wrap(s),bind(...v){return wrap(s,v);}};}}};return{sql,env};
}
test('a persisted CRM administrator has full CRM visibility while primary ownership stays separate',async()=>{
 const actor=await attachVisibility({}, {...administrator});assert.equal(actor.isOwner,true);assert.equal(actor.isPrimaryOwner,false);assert.equal(actor.visibility.profile,'administrator');assert.equal(actor.visibility.scope,'all');assert.equal(isPrimaryOwner(actor),false);assert.equal(isCrmAdministrator(actor),true);
 const full={contacts:[{id:'private',notes:'private notes',monthly_override:1500}],users:[{id:'other',name:'Other staff'}],access:[{secret:'saved CRM connection'}],todos:[{assignee:'Other staff'}]};assert.equal(scopeSnapshot(full,actor),full);assert.equal(mergeScopedWrite(full,{...full,edited:true},actor).edited,true);
 const primary=await attachVisibility({}, {...owner});assert.equal(primary.isPrimaryOwner,true);assert.equal(primary.visibility.profile,'owner');
});
test('forged administrator visibility and nonprimary legacy owner role do not grant full access',async()=>{
 const env={DB:{prepare(){return{bind(){return{first:async()=>({sections_json:'[]',edit_sections_json:'[]',access_profile:'administrator',record_scope:'all'})};}};}}};
 for(const actor of [{...contributor,visibility:{profile:'administrator'},isOwner:true},{...contributor,roleCode:'owner_admin'}]){const result=await attachVisibility(env,actor);assert.equal(result.isOwner,false);assert.equal(result.isPrimaryOwner,false);assert.equal(result.visibility.profile,'contributor');assert.equal(result.visibility.scope,'assigned');}
});
test('role migration defines capability without granting it to an existing user',()=>{
 const f=fixture({role:false});try{const before=f.sql.prepare('SELECT id,role_id FROM users ORDER BY id').all();f.sql.exec(fs.readFileSync(new URL('./migrations/20261008_crm_administrator_role.sql',import.meta.url),'utf8'));assert.deepEqual(f.sql.prepare('SELECT id,role_id FROM users ORDER BY id').all(),before);assert.equal(f.sql.prepare("SELECT code FROM roles WHERE id='role_crm_admin'").get().code,'crm_admin');}finally{f.sql.close();}
});
test('explicit administrator creation stores its trusted role separately from contributor visibility constraints, without inviting',async()=>{
 const f=fixture();let sent=0;try{const result=await handleUsers(request('','POST',grant),f.env,owner,{sendMail:async()=>sent++});assert.equal(result.status,200);const value=await result.json(),row=f.sql.prepare('SELECT role_id,status FROM users WHERE id=?').get(value.id);assert.equal(row.role_id,'role_crm_admin');assert.equal(row.status,'active');const policy=f.sql.prepare('SELECT access_profile,record_scope FROM user_visibility WHERE user_id=?').get(value.id);assert.equal(policy.access_profile,'contributor');assert.equal(policy.record_scope,'assigned');assert.equal(value.profile,'administrator');assert.equal(value.scope,'all');assert.equal(sent,0);}finally{f.sql.close();}
});
test('a missing role migration or missing access acknowledgement fails before creation or promotion',async()=>{
 for(const {role,payload,status}of [{role:false,payload:grant,status:503},{role:true,payload:{...grant,administratorAcknowledged:false},status:400}]){const f=fixture({role});try{assert.equal((await handleUsers(request('','POST',payload),f.env,owner)).status,status);assert.equal(f.sql.prepare('SELECT COUNT(*) AS n FROM users').get().n,3);assert.equal((await handleUsers(request('u_staff','PUT',payload),f.env,owner)).status,status);assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE id='u_staff'").get().role_id,'role_contributor');}finally{f.sql.close();}}
});
test('secondary administrators cannot edit, disable or invite the primary account, nor change their own account',async()=>{
 const f=fixture();try{for(const [id,method,body]of [['u_ibrar','PUT',{...grant,status:'disabled'}],['u_ibrar/invite','POST',{}],['u_admin','PUT',{...grant,profile:'contributor',scope:'assigned'}]])assert.equal((await handleUsers(request(id,method,body),f.env,administrator)).status,409);assert.equal(f.sql.prepare("SELECT role_id,status FROM users WHERE id='u_ibrar'").get().status,'active');assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE id='u_admin'").get().role_id,'role_crm_admin');}finally{f.sql.close();}
});
test('administrator grants and demotions preserve current ordinary staff restrictions and organization isolation',async()=>{
 const f=fixture();try{assert.equal((await handleUsers(request('u_staff','PUT',grant),f.env,contributor)).status,403);assert.equal((await handleUsers(request('u_staff','PUT',grant),f.env,{...owner,orgId:'other'})).status,404);assert.equal((await handleUsers(request('u_staff','PUT',grant),f.env,administrator)).status,200);assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE id='u_staff'").get().role_id,'role_crm_admin');const demotion={status:'active',profile:'sales_associate',scope:'assigned',sections:['contacts'],editSections:['contacts']};assert.equal((await handleUsers(request('u_staff','PUT',demotion),f.env,owner)).status,200);assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE id='u_staff'").get().role_id,'role_contributor');const policy=f.sql.prepare("SELECT access_profile,record_scope FROM user_visibility WHERE user_id='u_staff'").get();assert.equal(policy.access_profile,'sales_associate');assert.equal(policy.record_scope,'assigned');}finally{f.sql.close();}
});
test('administrator roster identifies actual target roles and protected primary, independent of the viewing administrator',async()=>{
 const f=fixture();try{const result=await handleUsers(request(),f.env,administrator),body=await result.json();assert.equal(result.status,200);assert.equal(body.actorId,administrator.id);const primary=body.users.find(u=>u.id==='u_ibrar'),secondary=body.users.find(u=>u.id==='u_admin'),staff=body.users.find(u=>u.id==='u_staff');assert.equal(primary.isPrimaryOwner,true);assert.equal(primary.profile,'owner');assert.equal(secondary.isPrimaryOwner,false);assert.equal(secondary.profile,'administrator');assert.equal(staff.isOwner,false);assert.ok(body.profiles.some(p=>p.id==='administrator'));const canonical=await canonicalUsers(f.env,'org1');assert.equal(canonical.find(u=>u.auth_user_id==='u_admin').role,'CRM administrator');}finally{f.sql.close();}
});
test('failed visibility persistence never grants a new administrator role',async()=>{
 const f=fixture(),prepare=f.env.DB.prepare;f.env.DB.prepare=q=>{if(q.startsWith('INSERT INTO user_visibility'))throw Error('Storage unavailable');return prepare(q);};
 try{assert.equal((await handleUsers(request('','POST',grant),f.env,owner)).status,500);assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE email='newadmin@example.test'").get().role_id,'role_contributor');assert.equal((await handleUsers(request('u_staff','PUT',grant),f.env,owner)).status,500);assert.equal(f.sql.prepare("SELECT role_id FROM users WHERE id='u_staff'").get().role_id,'role_contributor');}finally{f.sql.close();}
});
