import test from 'node:test';import assert from 'node:assert/strict';import {runNightlyBackup,pruneOldBackups} from './backups.mjs';import {diagnosticMailOrigin} from './provider-safety.mjs';
function fixture(fail=false){let saved;const env={DB:{prepare(sql){return {async all(){if(sql.includes('sqlite_master'))return {results:['crm_snapshot','zoom_calls','zoho_mail_meta','users','sessions','zoho_oauth_tokens','_cf_KV'].map(name=>({name}))};if(fail&&sql.includes('zoom_calls'))throw Error('Unavailable');return {results:sql.includes('users')?[{id:'u1',password_hash:'private'}]:[{id:'r1'}]};}};}},FILES:{async put(key,body){saved={key,payload:JSON.parse(body)};},async list(){return {objects:[],truncated:false};},async delete(){}}};return {env,get saved(){return saved;}};}
test('backup discovers integration tables while excluding sessions and OAuth credentials',async()=>{let f=fixture();let result=await runNightlyBackup(f.env);assert.equal(result.tableCount,4);assert.equal(f.saved.payload.status,'complete');assert.deepEqual(Object.keys(f.saved.payload.tables),['crm_snapshot','zoom_calls','zoho_mail_meta','users']);assert.equal(f.saved.payload.tables.users[0].password_hash,undefined);});
test('partial backup persists recoverable data and rejects so scheduled alert fires',async()=>{let f=fixture(true);await assert.rejects(runNightlyBackup(f.env),/Partial backup.*zoom_calls/);assert.equal(f.saved.payload.status,'partial');assert.match(f.saved.key,/\.partial\.json$/);assert.ok(f.saved.payload.tables.crm_snapshot);});
test('backup retention scans every object page and preserves recent backups',async()=>{let deleted=[],seen=[];let env={FILES:{async list(opts){seen.push(opts.cursor);return opts.cursor?{objects:[{key:'backups/2026-10-09T00-00-00-000Z.json'},{key:'backups/2026-07-01T00-00-00-000Z.json'}],truncated:false}:{objects:[{key:'backups/2026-06-01T00-00-00-000Z.json'}],truncated:true,cursor:'next'};},async delete(keys){deleted.push(...keys);}}};await pruneOldBackups(env,'2026-10-10T00:00:00Z');assert.deepEqual(seen,[undefined,'next']);assert.equal(deleted.length,2);assert.ok(deleted.every(k=>!k.includes('10-09')));});
test('retention errors surface instead of silently reporting a healthy backup',async()=>{let env={FILES:{async list(){throw Error('R2 failed');}}};await assert.rejects(pruneOldBackups(env,new Date().toISOString()),/R2 failed/);});
test('diagnostic server cannot send Zoho credentials to another origin or redirect path',()=>{const configured='https://mail.zoho.com';for(let host of ['https://attacker.example','http://mail.zoho.com','https://mail.zoho.com/redirect','https://mail.zoho.com/?target=evil','https://user:password@mail.zoho.com','https://mail.zoho.com:8443'])assert.throws(()=>diagnosticMailOrigin(configured,host));assert.equal(diagnosticMailOrigin(configured,configured),'https://mail.zoho.com');assert.equal(diagnosticMailOrigin('https://mail.zoho.eu',null),'https://mail.zoho.eu');});
import {handleZoomWebhook,verifyAccessJwt} from './worker.js';import {createHmac} from 'node:crypto';
function webhookFixture(){let inserted=false,processed=0,fail=true,updates=0;return {env:{ZOOM_WEBHOOK_SECRET_TOKEN:'fictional-secret',DB:{prepare(sql){let values=[];return {bind(...v){values=v;return this;},async run(){if(sql.startsWith('INSERT OR IGNORE INTO zoom_webhook')){const changes=inserted?0:1;inserted=true;return {meta:{changes}};}if(sql.startsWith('UPDATE zoom_webhook')){processed=1;updates++;return {meta:{changes:1}};}return {meta:{changes:1}};},async first(){if(sql.startsWith('SELECT processed'))return {processed};if(fail)throw Error('Temporary D1 failure');return null;},async all(){return {results:[]};}};}}},recover(){fail=false;},get processed(){return processed;},get updates(){return updates;}};}
function signedEvent(event='phone.caller_ended'){let raw=JSON.stringify({event,payload:{object:{call_id:'fictional-call'}}}),ts=String(Math.floor(Date.now()/1000));let sig='v0='+createHmac('sha256','fictional-secret').update('v0:'+ts+':'+raw).digest('hex');return new Request('https://crm.sereneop.com/zoom/webhook',{method:'POST',body:raw,headers:{'x-zm-request-timestamp':ts,'x-zm-signature':sig}});}
test('failed Zoom reconciliation remains unprocessed and asks Zoom to retry',async()=>{let f=webhookFixture();let r=await handleZoomWebhook(signedEvent(),f.env);assert.equal(r.status,503);assert.equal(f.processed,0);assert.equal(f.updates,0);});
test('an unprocessed duplicate Zoom event is retried and completed events are deduplicated',async()=>{let f=webhookFixture();await handleZoomWebhook(signedEvent(),f.env);f.recover();let r=await handleZoomWebhook(signedEvent(),f.env);assert.equal(r.status,200);assert.equal(f.processed,1);r=await handleZoomWebhook(signedEvent(),f.env);assert.equal((await r.json()).duplicate,true);assert.equal(f.updates,1);});
test('Zoom rejects invalid webhook signatures before reading or changing the database',async()=>{let f=webhookFixture();let req=signedEvent();req.headers.set('x-zm-signature','v0=bad');assert.equal((await handleZoomWebhook(req,f.env)).status,401);assert.equal(f.updates,0);});
test('Access refuses missing expiration, wrong issuer and unsupported algorithms before key lookup',async()=>{const env={ACCESS_TEAM_DOMAIN:'example.cloudflareaccess.com',ACCESS_AUD:'crm'};const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');let claims={iss:'https://example.cloudflareaccess.com',exp:Math.floor(Date.now()/1000)+300,aud:['crm'],email:'qa@example.invalid'};for(let [head,body] of [[{alg:'HS256',kid:'k'},claims],[{alg:'RS256',kid:'k'},{...claims,iss:'https://wrong.example'}],[{alg:'RS256',kid:'k'},{...claims,exp:undefined}]]){const req=new Request('https://crm.sereneop.com/api/me',{headers:{'Cf-Access-Jwt-Assertion':encode(head)+'.'+encode(body)+'.eA'}});assert.equal((await verifyAccessJwt(req,env)).status,401);}});

import {generateKeyPairSync,sign} from 'node:crypto';
test('Access continues accepting a correctly signed, unexpired CRM identity',async t=>{const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk=publicKey.export({format:'jwk'});jwk.kid='review-key';t.mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({keys:[jwk]}),{status:200}));let encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');let header=encode({alg:'RS256',kid:'review-key'}),payload=encode({iss:'https://example.cloudflareaccess.com',exp:Math.floor(Date.now()/1000)+300,nbf:Math.floor(Date.now()/1000)-10,aud:['crm'],email:'qa@example.invalid'}),input=header+'.'+payload,signature=sign('RSA-SHA256',Buffer.from(input),privateKey).toString('base64url');let req=new Request('https://crm.sereneop.com/api/me',{headers:{'Cf-Access-Jwt-Assertion':input+'.'+signature}});assert.equal((await verifyAccessJwt(req,{ACCESS_TEAM_DOMAIN:'example.cloudflareaccess.com',ACCESS_AUD:'crm'})).ok,true);});
import {FRONTEND_FILES,buildPages} from '../scripts/build-pages.mjs';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
test('Pages build copies the entrypoint and headers separately and excludes private backend files',()=>{let root=fs.mkdtempSync(path.join(os.tmpdir(),'serene-build-'));try{fs.mkdirSync(path.join(root,'assets'));for(let file of FRONTEND_FILES)fs.writeFileSync(path.join(root,file),'fixture:'+file);fs.mkdirSync(path.join(root,'worker'));fs.writeFileSync(path.join(root,'worker','private.txt'),'not public');let out=buildPages(root);assert.equal(fs.readFileSync(path.join(out,'index.html'),'utf8'),'fixture:index.html');assert.equal(fs.readFileSync(path.join(out,'_headers'),'utf8'),'fixture:_headers');assert.equal(fs.existsSync(path.join(out,'worker')),false);fs.writeFileSync(path.join(out,'unexpected.txt'),'do not publish');assert.throws(()=>buildPages(root),/Unexpected build output/);}finally{if(!path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep))throw Error("Temporary test folder is outside its intended root.");fs.rmSync(root,{recursive:true,force:true});}});
import {zohoAccountsOrigin} from './provider-safety.mjs';import {handleZohoOAuthCallback} from './worker.js';
test('Zoho regional OAuth allows only official HTTPS accounts servers',()=>{for(let host of ['accounts.zoho.com','accounts.zoho.eu','accounts.zoho.in','accounts.zoho.com.au','accounts.zoho.com.cn','accounts.zoho.jp','accounts.zohocloud.ca','accounts.zoho.sa','accounts.zoho.ae'])assert.equal(zohoAccountsOrigin('https://'+host+'/'),'https://'+host);for(let v of ['https://attacker.example','https://accounts.zoho.com.attacker.example','http://accounts.zoho.com','https://accounts.zoho.com/path','https://user:secret@accounts.zoho.com','https://accounts.zoho.com:8443'])assert.throws(()=>zohoAccountsOrigin(v));});
test('Zoho diagnostics also reject untrusted configured mail domains',()=>{for(let v of ['https://mail.attacker.example','https://mail.zoho.com/redirect','https://mail.zoho.com:8443'])assert.throws(()=>diagnosticMailOrigin(v));});
test('Zoho callback never sends client credentials to an untrusted accounts-server',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw Error('Unexpected network call');});const env={ZOHO_CLIENT_ID:'fictional-client',ZOHO_CLIENT_SECRET:'fictional-secret',DB:{prepare(){return {bind(){return this;},async first(){return {org_id:'org1',created_at:new Date().toISOString()};},async run(){return {meta:{changes:1}};}};}}};let req=new Request('https://crm.sereneop.com/zoho/oauth/callback?code=fictional-code&state=fictional-state&accounts-server=https%3A%2F%2Fattacker.example');let res=await handleZohoOAuthCallback(req,env);assert.equal(res.status,302);assert.match(res.headers.get('location'),/invalid_accounts_server/);assert.equal(calls,0);});
