import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import recovery from './integrate-autosave-recovery.cjs';
import integration from './integrate-sales-autosave.cjs';
import baselines from './integrate-sales-save-baselines.cjs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),original=JSON.parse(html.match(/<script type="__bundler\/template">([\s\S]*?)<\/script>/)[1]),template=baselines.transform(integration.transform(recovery.transform(original))),code=template.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
const plain=value=>JSON.parse(JSON.stringify(value));
const response=(contact,at='after')=>new Response(JSON.stringify({data:{ok:true,updatedAt:at},contact}),{headers:{'content-type':'application/json',ETag:JSON.stringify(at)}});
function fixture(){const timers=[];const context={Date,Intl,JSON,Math,URL,URLSearchParams,structuredClone,console,location:{hostname:'crm.sereneop.com',origin:'https://crm.sereneop.com'},window:{location:{reload(){}}},setTimeout:(fn,delay)=>{const timer={fn,delay};timers.push(timer);return timer;},clearTimeout(){},DCLogic:class{setState(value,cb){this.state={...this.state,...(typeof value==='function'?value(this.state):value)};cb?.();}}};vm.createContext(context);vm.runInContext(code+';globalThis.ReviewComponent=Component;',context);const c=new context.ReviewComponent();c.props={};c.toast=()=>{};c.state={...c.state,db:c.normalizeScopedWorkspace({org:{id:'org1'},users:[{id:'u_sales',name:'Sales Person',email:'sales@example.invalid'}],contacts:[{id:'c1',name:'QA Prospect',sales_notes:'Before',status:'Not contacted',city:'Before city',assigned_to_me:true},{id:'c2',name:'Other Prospect',sales_notes:'Other original',status:'Not contacted'}],deals:[{id:'d1',contact_id:'c1',stage:'Demo scheduled',sales_notes:'Before deal notes'}],checklists:{precall:[],onboarding:[]}}),accessUser:{isOwner:false,email:'sales@example.invalid',visibility:{profile:'sales_associate',scope:'all_sales',sections:['contacts','pipeline','calls'],editSections:['contacts','pipeline','calls']}},authChecked:true,meId:'u_sales',meIdUnresolved:false,dbLoadFailed:false};c._saveEpoch=0;c._savedEpoch=0;c._snapshotEtag='"before"';c.adoptSalesBaseline(c.state.db);return{c,timers};}
test('a note edit uses a small PATCH with only its original and changed note, and a confirmed write clears dirty state',async()=>{
 const {c}=fixture();let sent;c.apiFetch=async(path,options)=>{sent={path,options};return response({...c.state.db.contacts[0],sales_notes:'Conversation outcome'});};c.patch('contacts','c1','sales_notes','Conversation outcome');await c.flushDb();assert.equal(sent.path,'/api/sales/contacts/c1');assert.equal(sent.options.method,'PATCH');assert.deepEqual(JSON.parse(sent.options.body),{patch:{sales_notes:'Conversation outcome'},base:{sales_notes:'Before'}});assert.ok(sent.options.body.length<150);assert.equal(c.state.saveStatus,'saved');assert.equal(c._savedEpoch,c._saveEpoch);assert.equal(c._snapshotEtag,'"after"');assert.deepEqual(plain(c.workspaceWritePayload().contacts),[]);
});
test('typing during the first save is kept locally and saved next with the first confirmed note as its base',async()=>{
 const {c}=fixture(),calls=[];let resolve;c.apiFetch=(path,options)=>{calls.push({path,body:JSON.parse(options.body)});if(calls.length===1)return new Promise(done=>{resolve=done;});return Promise.resolve(response({...c.state.db.contacts[0],sales_notes:calls[1].body.patch.sales_notes},'after-second'));};c.patch('contacts','c1','sales_notes','First note');const first=c.flushDb();c.patch('contacts','c1','sales_notes','More complete note');resolve(response({...c.state.db.contacts[0],sales_notes:'First note'},'after-first'));await first;await new Promise(done=>setImmediate(done));assert.equal(calls.length,2);assert.deepEqual(calls[1].body,{patch:{sales_notes:'More complete note'},base:{sales_notes:'First note'}});assert.equal(c.state.db.contacts[0].sales_notes,'More complete note');assert.equal(c._savedEpoch,c._saveEpoch);assert.equal(c.state.saveStatus,'saved');
});
test('canonical independent field updates appear in the contact and later deal saves contain no stale contact fields',async()=>{
 const {c}=fixture();c.apiFetch=async()=>response({...c.state.db.contacts[0],sales_notes:'Saved note',city:'Another user latest city'});c.patch('contacts','c1','sales_notes','Saved note');await c.flushDb();assert.equal(c.state.db.contacts[0].city,'Another user latest city');c.patch('deals','d1','sales_notes','Changed deal note');const payload=c.workspaceWritePayload();assert.deepEqual(plain(payload.contacts),[]);assert.deepEqual(plain(payload.deals),[{id:'d1',sales_notes:'Changed deal note'}]);
});
test('a failed or conflicting small save keeps note text unsaved and retains the original baseline',async()=>{
 for(const status of [503,409]){const {c}=fixture();c.apiFetch=async()=>new Response(JSON.stringify({error:'The save was not committed'}),{status,headers:{'content-type':'application/json'}});c.patch('contacts','c1','sales_notes','Keep this complete note');await c.flushDb();assert.equal(c._savedEpoch,0);assert.equal(c.state.db.contacts[0].sales_notes,'Keep this complete note');assert.equal(c._salesContactBaseline[0].sales_notes,'Before');assert.equal(c.state.saveStatus,'error');assert.equal(c.state.saveConflict,status===409);}
});
test('a contact edit together with another workspace mutation uses full versioned persistence rather than losing the other mutation',async()=>{
 const {c}=fixture();let sent;c.apiFetch=async(path,options)=>{sent={path,body:JSON.parse(options.body)};return new Response(JSON.stringify({data:{ok:true,updatedAt:'after'},snapshot:c.state.db}),{headers:{'content-type':'application/json'}});};c.patch('contacts','c1','sales_notes','Saved note');c.commit(db=>{db.user_prefs.u_sales={contactViews:[{name:'My saved view'}]};});await c.flushDb();assert.equal(sent.path,'/api/db');assert.deepEqual(sent.body.contacts,[{id:'c1',sales_notes:'Saved note'}]);assert.equal(sent.body.user_prefs.u_sales.contactViews[0].name,'My saved view');assert.equal(c.state.saveStatus,'saved');
});
test('a clean canonical refresh after a call adopts the new contact baseline without manufacturing another edit',async()=>{
 const {c}=fixture(),fresh=plain(c.state.db);fresh.contacts[0].status='Contacted';fresh.contacts[0].sales_notes='Latest shared context';c.apiFetch=async()=>new Response(JSON.stringify({data:fresh,updatedAt:'after-call'}),{headers:{'content-type':'application/json'}});await c.refreshAuditDocuments();assert.equal(c.state.db.contacts[0].status,'Contacted');assert.equal(c._salesContactBaseline[0].status,'Contacted');assert.deepEqual(plain(c.salesContactChanges()),[]);assert.equal(c._snapshotEtag,'"after-call"');
});
test('an edit during a canonical refresh stays dirty and the old baseline is retained',async()=>{
 const {c}=fixture(),fresh=plain(c.state.db);fresh.contacts[0].sales_notes='Other server context';let complete;c.apiFetch=()=>new Promise(resolve=>{complete=resolve;});const refresh=c.refreshAuditDocuments();c.patch('contacts','c1','sales_notes','My note while refreshing');complete(new Response(JSON.stringify({data:fresh,updatedAt:'after-call'}),{headers:{'content-type':'application/json'}}));await refresh;assert.equal(c.state.db.contacts[0].sales_notes,'My note while refreshing');assert.equal(c._salesContactBaseline[0].sales_notes,'Before');assert.equal(c._snapshotEtag,'"before"');assert.equal(c.salesContactChanges()[0].base.sales_notes,'Before');
});
test('archiving removes only that contact and its deal baseline while preserving a concurrent edit on another contact',async()=>{
 const {c}=fixture();let complete;c.apiFetch=()=>new Promise(resolve=>{complete=resolve;});const archived=c.submitContactArchive('c1','No longer interested');c.patch('contacts','c2','sales_notes','New note while archiving');complete(new Response(JSON.stringify({data:{ok:true,id:'c1',at:'2026-10-08T12:00:00Z',reason:'No longer interested'},updatedAt:'after-archive'}),{headers:{'content-type':'application/json'}}));await archived;assert.equal(c.state.db.contacts.some(row=>row.id==='c1'),false);assert.equal(c._salesContactBaseline.some(row=>row.id==='c1'),false);assert.equal(c._salesDealBaseline.some(row=>row.contact_id==='c1'),false);assert.equal(c._salesContactBaseline.find(row=>row.id==='c2').sales_notes,'Other original');assert.equal(c.state.db.contacts.find(row=>row.id==='c2').sales_notes,'New note while archiving');assert.ok(c._saveEpoch>c._savedEpoch);assert.deepEqual(plain(c.salesContactChanges()),[{id:'c2',patch:{sales_notes:'New note while archiving'},base:{sales_notes:'Other original'}}]);
});
