import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {inviteUser,policyWithEmail,invitationEmail,revokeUserAccess} from './user-invitations.mjs';
import {handleUsers} from './user-access.mjs';
const owner={id:'u_ibrar',orgId:'org1',isOwner:true};
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE users(id TEXT PRIMARY KEY,org_id TEXT,name TEXT,email TEXT UNIQUE,role_id TEXT,status TEXT,created_at TEXT DEFAULT 'now',updated_at TEXT,deleted_at TEXT);CREATE TABLE user_visibility(org_id TEXT,user_id TEXT,sections_json TEXT,edit_sections_json TEXT,updated_at TEXT,PRIMARY KEY(org_id,user_id));INSERT INTO users VALUES('staff','org1','A <Staff>','staff@example.com','role_contributor','active','now',NULL,NULL);INSERT INTO users VALUES('u_ibrar','org1','Owner','owner@example.com','role_owner','active','now',NULL,NULL);");sql.exec(readFileSync(new URL('./migrations/20261007_user_invitations.sql',import.meta.url),'utf8'));const wrap=(s,v=[])=>({first:async()=>s.get(...v)||null,all:async()=>({results:s.all(...v)}),run:async()=>({meta:{changes:Number(s.run(...v).changes)}})});const env={CRM_ACCESS_API_TOKEN:'test-token',CRM_ACCESS_ACCOUNT_ID:'account',CRM_ACCESS_POLICY_ID:'policy',DB:{prepare(q){const s=sql.prepare(q);return {...wrap(s),bind(...v){return wrap(s,v);}};}}};let policy={name:'Serene Ops CRM invitations',decision:'allow',include:[{email:{email:'owner@example.com'}}],exclude:[],require:[],session_duration:'24h'};let sends=0,updates=0;const services={fetch:async(url,options)=>{assert.match(url,/^https:\/\/api.cloudflare.com\/client\/v4\/accounts\/account\/access\/policies\/policy$/);if(options.method==='PUT'){updates++;policy=JSON.parse(options.body);}return Response.json({success:true,result:policy});},sendMail:async(actor,message)=>{assert.equal(actor.id,owner.id);assert.equal(message.toAddress,'staff@example.com');sends++;}};return {sql,env,services,get sends(){return sends;},get updates(){return updates;},get policy(){return policy;}};}
test('policy update adds only exact email and preserves security conditions',()=>{const p={name:'Serene Ops CRM invitations',decision:'allow',include:[{email:{email:'owner@example.com'}}],require:[{login_method:{id:'otp'}}],exclude:[{email:{email:'blocked@example.com'}}],approval_required:true,session_duration:'12h'};const out=policyWithEmail(p,'STAFF@EXAMPLE.COM',true);assert.equal(out.include.length,2);assert.deepEqual(out.require,p.require);assert.deepEqual(out.exclude,p.exclude);assert.equal(out.approval_required,true);assert.equal(out.session_duration,'12h');assert.equal(p.include.length,1);assert.throws(()=>policyWithEmail({...p,include:[{everyone:{}}]},'staff@example.com',true),/review/);assert.throws(()=>policyWithEmail({...p,name:'Other application'},'staff@example.com',true),/review/);});
test('invitation approves first, sends once, and records status; repeat submit does not duplicate email',async()=>{const f=fixture();try{assert.equal((await inviteUser(f.env,owner,'staff',{},f.services)).ok,true);assert.equal(f.policy.include.length,2);assert.equal(f.sends,1);assert.equal(f.sql.prepare('SELECT status,access_status FROM user_invitations').get().status,'sent');assert.equal((await inviteUser(f.env,owner,'staff',{},f.services)).ok,true);assert.equal(f.sends,1);assert.equal(f.updates,1);}finally{f.sql.close();}});
test('failed Access approval sends no invitation and leaves CRM account unchanged',async()=>{const f=fixture();try{const out=await inviteUser(f.env,owner,'staff',{}, {...f.services,fetch:async()=>Response.json({success:false},{status:403})});assert.equal(out.ok,false);assert.equal(f.sends,0);assert.equal(f.sql.prepare('SELECT status FROM users WHERE id=?').get('staff').status,'active');assert.equal(f.sql.prepare('SELECT status FROM user_invitations').get().status,'failed');}finally{f.sql.close();}});
test('unknown email result is not automatically retried',async()=>{const f=fixture();try{const out=await inviteUser(f.env,owner,'staff',{}, {...f.services,sendMail:async()=>{throw Error('timeout');}});assert.equal(out.invitationStatus,'send_unknown');assert.equal(f.policy.include.length,2);const retry=await inviteUser(f.env,owner,'staff',{},f.services);assert.equal(retry.invitationStatus,'send_unknown');assert.equal(f.sends,0);}finally{f.sql.close();}});
test('disabled users, contributors and another organization cannot send invites',async()=>{const f=fixture();try{await assert.rejects(inviteUser(f.env,{...owner,isOwner:false},'staff',{},f.services),/Only CRM administrators/);await assert.rejects(inviteUser(f.env,{...owner,orgId:'other'},'staff',{},f.services),/active/);f.sql.exec("UPDATE users SET status='disabled' WHERE id='staff'");await assert.rejects(inviteUser(f.env,owner,'staff',{},f.services),/active/);assert.equal(f.sends,0);}finally{f.sql.close();}});
test('concurrent invitation lock prevents policy overwrite and sending',async()=>{const f=fixture();try{f.sql.prepare('INSERT INTO user_invitation_locks VALUES(?,?,?)').run(owner.orgId,'other-lease',Date.now()+180000);await assert.rejects(inviteUser(f.env,owner,'staff',{},f.services),/processing/);assert.equal(f.updates,0);assert.equal(f.sends,0);}finally{f.sql.close();}});
test('disabling removes managed access without removing owner and prevents invitations',async()=>{const f=fixture();try{await inviteUser(f.env,owner,'staff',{},f.services);const req=new Request('https://crm.test/api/users/staff',{method:'PUT',body:JSON.stringify({status:'disabled',sections:['work'],editSections:[]})});const response=await handleUsers(req,f.env,owner,f.services);assert.equal(response.status,200);assert.deepEqual(f.policy.include,[{email:{email:'owner@example.com'}}]);assert.equal(f.sql.prepare('SELECT status FROM users WHERE id=?').get('staff').status,'disabled');assert.equal(f.sql.prepare('SELECT status FROM user_invitations').get().status,'disabled');}finally{f.sql.close();}});
test('mail template escapes name and does not include credentials or access tokens',()=>{const mail=invitationEmail({name:'<script>attack</script>',email:'staff@example.com'});assert.match(mail.content,/&lt;script&gt;/);assert.doesNotMatch(mail.content,/<script>|token=|password=/);assert.match(mail.content,/https:\/\/crm.sereneop.com/);});
test('new account can be saved with invitation failure, and invite endpoint is organization scoped',async()=>{const f=fixture();try{const req=new Request('https://crm.test/api/users',{method:'POST',body:JSON.stringify({name:'New Person',email:'new@example.com',sections:['work'],editSections:[],invite:true})});const r=await handleUsers(req,{...f.env,CRM_ACCESS_API_TOKEN:null},owner,f.services);const result=await r.json();assert.equal(r.status,200);assert.equal(result.ok,false);assert.ok(result.id);assert.equal(f.sql.prepare('SELECT role_id FROM users WHERE id=?').get(result.id).role_id,'role_contributor');const list=await handleUsers(new Request('https://crm.test/api/users'),f.env,owner,f.services);assert.equal((await list.json()).invitationReady,true);const bad=await handleUsers(new Request('https://crm.test/api/users/staff/invite/extra',{method:'POST',body:'{}'}),f.env,owner,f.services);assert.equal(bad.status,404);}finally{f.sql.close();}});
test('disabling remains accurately reported when another invitation holds the synchronization lock',async()=>{const f=fixture();try{
 f.sql.prepare('INSERT INTO user_invitation_locks VALUES(?,?,?)').run(owner.orgId,'other-lease',Date.now()+180000);
 const req=new Request('https://crm.test/api/users/staff',{method:'PUT',body:JSON.stringify({status:'disabled',sections:['work'],editSections:[]})});
 const result=await handleUsers(req,f.env,owner,f.services);assert.equal(result.status,200);assert.match((await result.json()).accessNotice,/disabled in the CRM/);assert.equal(f.sql.prepare('SELECT status FROM users WHERE id=?').get('staff').status,'disabled');assert.equal(f.sends,0);assert.equal(f.updates,0);
 }finally{f.sql.close();}});
test('provisioning refuses a duplicate display name without inviting or granting legacy assignments',async()=>{const f=fixture();try{
 const req=new Request('https://crm.test/api/users',{method:'POST',body:JSON.stringify({name:' Owner ',email:'different@example.com',sections:['work'],editSections:['work'],invite:true})});
 const result=await handleUsers(req,f.env,owner,f.services);assert.equal(result.status,409);assert.match((await result.json()).error,/display name/);assert.equal(f.sql.prepare('SELECT COUNT(*) AS n FROM users').get().n,2);assert.equal(f.sends,0);assert.equal(f.updates,0);
 }finally{f.sql.close();}});
